

  insert into [Course] values ('76736334-BB42-447B-97D5-94384F79D2A9', 'General Security Practice', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'','', 'E,D,C,B & A',2500 );
  insert into [Course] values ('80061285-CBA3-4B1B-A940-EFE0D4A972C7', 'Specialist Security Practice', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'','Civilian – Handgun, Shortgun and Rifle Business – Handgun, shortgun and Rifle', 'E,D,C,B & A',2500 );
  insert into [Course] values ('2893E6AB-E1D8-4BD7-AB73-98F2B678AD28', 'VIP (Close Protection) Security Practice', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'VIP, Advanced driving, Threat analysis, Close combat','Civilian – Handgun, Shortgun and Rifle Business – Handgun, shortgun and Rifle', 'E,D,C,B & A',2500 );
  insert into [Course] values ('4A9A703A-4A24-4523-BBB8-67646EC17351', 'Instructor Security Practice', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'Instructor, assessor and moderator training','Civilian – Handgun, Shortgun and Rifle Business – Handgun, shortgun and Rifle', 'E,D,C,B & A',2500 );
  insert into [Course] values ('F9669F4B-3FDE-4479-BAB3-F917E44A6C18', 'Plant Production – Hydroponic (Tunnel farming)', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'','', '',2500 );
  insert into [Course] values ('A06A9194-76F6-4242-9F5D-FD195B916A8D', 'Building and Civil Construction', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'','', '',2500 );
  insert into [Course] values ('66DADBE8-23AD-471D-9A2A-528D5CCCDBB3', 'Mechatronics', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'','', '',2500 );
  insert into [Course] values ('43E61405-C4D9-4B74-934E-70EC9EA9BC1F', 'Welding', 'Student to receive protective clothing and working tools.','1 year – (6 months class and 6 months’ workplace)', GETDATE(),'','', '',2500 );